# Generated by Django 5.2.9 on 2026-01-30 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
    ]
