# Generated by Django 5.2.9 on 2026-01-18 16:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Businessmen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('age', models.IntegerField()),
                ('phone_number', models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+998xxxxxxxxx'. Up to 9 digits allowed.", regex='^\\+998\\d{9}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+998xxxxxxxxx'. Up to 9 digits allowed.", regex='^\\+998\\d{9}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('business_type', models.CharField(max_length=100)),
                ('business_info', models.TextField()),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('business_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diplom_app.businessmen')),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('business', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='diplom_app.business')),
                ('businessman', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='diplom_app.businessmen')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('info', models.TextField()),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='product_images/%Y/%m/%d/')),
                ('maxsulot_soni', models.IntegerField(default=0)),
                ('maxsulot_birligi', models.CharField(choices=[('kg', 'Kilogramm'), ('dona', 'Dona/Shtat'), ('litr', 'Litr'), ('metr', 'Metr')], default='dona', max_length=10)),
                ('bisness_turi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diplom_app.business')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diplom_app.categories')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdor', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diplom_app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diplom_app.users')),
            ],
        ),
    ]
