# Generated by Django 5.2.9 on 2026-01-25 08:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Businessmen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+998xxxxxxxxx'. Up to 9 digits allowed.", regex='^\\+998\\d{9}$')])),
                ('is_businessman', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='business_logos/%Y/%m/%d/')),
                ('business_info', models.TextField()),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('business_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diplom_app.businessmen')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='diplom_app.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('info', models.TextField()),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='product_images/%Y/%m/%d/')),
                ('maxsulot_soni', models.IntegerField(default=0)),
                ('maxsulot_birligi', models.CharField(choices=[('kg', 'Kilogramm'), ('dona', 'Dona/Shtat'), ('litr', 'Litr'), ('metr', 'Metr')], default='dona', max_length=10)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('business_turi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diplom_app.business')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diplom_app.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Zakaz', 'Zakaz')], default='Zakaz', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('miqdor', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diplom_app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diplom_app.users')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price_at_purchase', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Yetkazildi', 'Yetkazildi'), ('Bekor qilindi', 'Bekor qilindi'), ('Jarayonda', 'Jarayonda'), ('Zakaz', 'Zakaz')], default='Zakaz', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='diplom_app.orders')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diplom_app.product')),
            ],
        ),
        migrations.AddField(
            model_name='businessmen',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diplom_app.users'),
        ),
    ]
